export const languages = {
  en: "English",
  "zh-CN": "Mandarin Chinese",
  hi: "Hindi",
  es: "Spanish",
  ar: "Standard Arabic",
  fr: "French",
  bn: "Bengali",
  pt: "Portuguese",
  ur: "Urdu",
  id: "Indonesian",
  de: "German",
  ja: "Japanese",
  uk: "Ukrainian",
};
